/**
 * ImageMate Studio - Tool Metadata & Information
 * Provides distinctive non-Photoshop names, modern icons, and descriptions.
 */

import {
  Pointer,
  BoxSelect,
  CircleDashed,
  Spline,
  Orbit,
  Target,
  Frame,
  FlaskConical,
  Paintbrush,
  PenLine,
  CopyPlus,
  Bandage,
  SquareMinus,
  Layers,
  Droplet,
  Wind,
  Flame,
  Waves,
  SunMedium,
  SunDim,
  Contrast,
  Feather,
  CaseSensitive,
  Boxes,
  Square,
  Circle,
  Hexagon,
  Star,
  Minus,
  ArrowRight,
  Grab,
  Search,
  LucideIcon,
} from 'lucide-react';
import { ToolType } from '../types/imagemate';

export interface ToolMeta {
  type: ToolType;
  name: string;
  groupName: string;
  category: 'Select' | 'Paint' | 'Retouch' | 'Vector' | 'Navigate';
  shortcut: string;
  icon: LucideIcon;
  description: string;
}

export const TOOL_REGISTRY: Record<ToolType, ToolMeta> = {
  move: {
    type: 'move',
    name: 'Pointer & Transform',
    groupName: 'Pointer & Transform',
    category: 'Select',
    shortcut: 'V',
    icon: Pointer,
    description: 'Select, reposition, and transform layers and objects',
  },
  'marquee-rect': {
    type: 'marquee-rect',
    name: 'Box Frame Select',
    groupName: 'Frame Selector',
    category: 'Select',
    shortcut: 'M',
    icon: BoxSelect,
    description: 'Create rectangular and square selection bounds',
  },
  'marquee-ellipse': {
    type: 'marquee-ellipse',
    name: 'Oval Frame Select',
    groupName: 'Frame Selector',
    category: 'Select',
    shortcut: 'M',
    icon: CircleDashed,
    description: 'Create elliptical and circular selection bounds',
  },
  'lasso-free': {
    type: 'lasso-free',
    name: 'Freehand Contour',
    groupName: 'Contour Selector',
    category: 'Select',
    shortcut: 'L',
    icon: Spline,
    description: 'Draw freeform boundary selections with fluid curve control',
  },
  'lasso-poly': {
    type: 'lasso-poly',
    name: 'Polygon Segment Contour',
    groupName: 'Contour Selector',
    category: 'Select',
    shortcut: 'L',
    icon: Orbit,
    description: 'Create multi-point straight-line polygonal selections',
  },
  'magic-wand': {
    type: 'magic-wand',
    name: 'Chroma & Tone Wand',
    groupName: 'Chroma & Tone Wand',
    category: 'Select',
    shortcut: 'W',
    icon: Target,
    description: 'Select contiguous regions based on color similarity and tolerance',
  },
  crop: {
    type: 'crop',
    name: 'Canvas Trimmer',
    groupName: 'Canvas Trimmer',
    category: 'Select',
    shortcut: 'C',
    icon: Frame,
    description: 'Reframe, trim, or expand the active document dimensions',
  },
  eyedropper: {
    type: 'eyedropper',
    name: 'Color Probe',
    groupName: 'Color Probe',
    category: 'Navigate',
    shortcut: 'I',
    icon: FlaskConical,
    description: 'Sample precise color values from any pixel on the canvas',
  },
  brush: {
    type: 'brush',
    name: 'Paint Stylus',
    groupName: 'Paint Stylus',
    category: 'Paint',
    shortcut: 'B',
    icon: Paintbrush,
    description: 'Paint strokes with pressure sensitivity, jitter, and dynamic textures',
  },
  pencil: {
    type: 'pencil',
    name: 'Precision Scribe',
    groupName: 'Paint Stylus',
    category: 'Paint',
    shortcut: 'B',
    icon: PenLine,
    description: 'Crisp, hard-edged pixel art and drafting lines',
  },
  'clone-stamp': {
    type: 'clone-stamp',
    name: 'Texture Replicator',
    groupName: 'Texture Replicator',
    category: 'Retouch',
    shortcut: 'S',
    icon: CopyPlus,
    description: 'Sample source coordinates with Alt+Click to duplicate texture',
  },
  'spot-healing': {
    type: 'spot-healing',
    name: 'Surface Healer',
    groupName: 'Surface Healer',
    category: 'Retouch',
    shortcut: 'J',
    icon: Bandage,
    description: 'Seamlessly blend and remove surface blemishes and artifacts',
  },
  eraser: {
    type: 'eraser',
    name: 'Pigment Clearer',
    groupName: 'Pigment Clearer',
    category: 'Paint',
    shortcut: 'E',
    icon: SquareMinus,
    description: 'Erase painted content to transparent or background color',
  },
  gradient: {
    type: 'gradient',
    name: 'Gradient Flow',
    groupName: 'Color Flow & Fill',
    category: 'Paint',
    shortcut: 'G',
    icon: Layers,
    description: 'Cast smooth linear or radial multi-color transitions',
  },
  'paint-bucket': {
    type: 'paint-bucket',
    name: 'Flood Fill Bucket',
    groupName: 'Color Flow & Fill',
    category: 'Paint',
    shortcut: 'G',
    icon: Droplet,
    description: 'Instantly fill bounded regions with solid foreground color',
  },
  blur: {
    type: 'blur',
    name: 'Soft Focus',
    groupName: 'Focus & Diffusion',
    category: 'Retouch',
    shortcut: 'R',
    icon: Wind,
    description: 'Defocus and soften pixel transitions under the cursor',
  },
  sharpen: {
    type: 'sharpen',
    name: 'Edge Sharpener',
    groupName: 'Focus & Diffusion',
    category: 'Retouch',
    shortcut: 'R',
    icon: Flame,
    description: 'Enhance high-frequency contrast and edge definition',
  },
  smudge: {
    type: 'smudge',
    name: 'Pigment Smudge',
    groupName: 'Focus & Diffusion',
    category: 'Retouch',
    shortcut: 'R',
    icon: Waves,
    description: 'Smear and blend neighboring pixel pigments smoothly',
  },
  dodge: {
    type: 'dodge',
    name: 'Highlight Boost',
    groupName: 'Tone & Luminance',
    category: 'Retouch',
    shortcut: 'O',
    icon: SunMedium,
    description: 'Selectively brighten exposure and lift midtones/highlights',
  },
  burn: {
    type: 'burn',
    name: 'Shadow Deepen',
    groupName: 'Tone & Luminance',
    category: 'Retouch',
    shortcut: 'O',
    icon: SunDim,
    description: 'Deepen shadows and increase local tonal density',
  },
  sponge: {
    type: 'sponge',
    name: 'Color Vibrance',
    groupName: 'Tone & Luminance',
    category: 'Retouch',
    shortcut: 'O',
    icon: Contrast,
    description: 'Modulate color saturation and vibrance across strokes',
  },
  pen: {
    type: 'pen',
    name: 'Bezier Path Drafter',
    groupName: 'Bezier Path Drafter',
    category: 'Vector',
    shortcut: 'P',
    icon: Feather,
    description: 'Construct scalable vector curves and custom geometric outlines',
  },
  text: {
    type: 'text',
    name: 'Typography Inscription',
    groupName: 'Typography Inscription',
    category: 'Vector',
    shortcut: 'T',
    icon: CaseSensitive,
    description: 'Insert and style editable text with custom fonts and alignment',
  },
  'shape-rect': {
    type: 'shape-rect',
    name: 'Box Primitive',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: Square,
    description: 'Draw crisp rectangular vector shape primitives',
  },
  'shape-rounded': {
    type: 'shape-rounded',
    name: 'Filleted Box',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: Square,
    description: 'Draw rounded rectangle vector shape with corner radius',
  },
  'shape-ellipse': {
    type: 'shape-ellipse',
    name: 'Oval Primitive',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: Circle,
    description: 'Draw circle and oval vector shape primitives',
  },
  'shape-polygon': {
    type: 'shape-polygon',
    name: 'Hexagon Polygon',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: Hexagon,
    description: 'Draw regular multi-sided polygon vector shapes',
  },
  'shape-star': {
    type: 'shape-star',
    name: 'Starburst Primitive',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: Star,
    description: 'Draw multi-point starburst geometric vectors',
  },
  'shape-line': {
    type: 'shape-line',
    name: 'Linear Vector',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: Minus,
    description: 'Draw straight directional vector lines',
  },
  'shape-arrow': {
    type: 'shape-arrow',
    name: 'Vector Pointer',
    groupName: 'Vector Geometries',
    category: 'Vector',
    shortcut: 'U',
    icon: ArrowRight,
    description: 'Draw vector directional arrows with customizable arrowhead',
  },
  hand: {
    type: 'hand',
    name: 'Canvas Pan',
    groupName: 'Canvas Pan',
    category: 'Navigate',
    shortcut: 'H',
    icon: Grab,
    description: 'Freely pan and navigate the canvas viewport in any direction',
  },
  zoom: {
    type: 'zoom',
    name: 'View Magnifier',
    groupName: 'View Magnifier',
    category: 'Navigate',
    shortcut: 'Z',
    icon: Search,
    description: 'Magnify in (Left Click) or zoom out (Alt / Shift Click)',
  },
};

export const getToolMeta = (tool: ToolType): ToolMeta => {
  return (
    TOOL_REGISTRY[tool] || {
      type: tool,
      name: tool.replace('-', ' '),
      groupName: tool.replace('-', ' '),
      category: 'Paint',
      shortcut: '',
      icon: Paintbrush,
      description: '',
    }
  );
};
